version: '3.7'

services:
  ddf1: 
    image: codice/ddf:2.14.0-SNAPSHOT
    environment:
      SOLR_URL: "http://ddf1-solr:8983/solr"
      EXTERNAL_HTTPS_PORT: 443
      EXTERNAL_HTTP_PORT: 80
      JAVA_MAX_MEM: ${DIB_JAVA_MEM:-4}
      INSTALL_PROFILE: standard
      SSH_ENABLED: 'true'
    tty: true
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          memory: 3g
          cpus: '1.0'
      labels:
        - "traefik.enable=true"
        - "traefik.https.frontend.rule=Host: ddf1${DEPLOY_HOSTNAME_SUFFIX}.${DEPLOY_DOMAIN:-test}"
        - "traefik.https.protocol=https"
        - "traefik.https.port=8993"
        - "traefik.https.frontend.entryPoints=https"
        - "traefik.http.frontend.rule=Host: ddf1${DEPLOY_HOSTNAME_SUFFIX}.${DEPLOY_DOMAIN:-test}"
        - "traefik.http.protocol=http"
        - "traefik.http.port=8181"
        - "traefik.http.frontend.entryPoints=http"
    hostname: ddf1${DEPLOY_HOSTNAME_SUFFIX}.${DEPLOY_DOMAIN:-test}
    networks:
      - proxy
      - default
      - ddf1-solr

  ddf1-solr:
    image: codice/ddf-solr:2.14.0-SNAPSHOT
    environment:
      CORES: "catalog metacard_cache alerts preferences subscriptions notification activity workspace"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.5'
        reservations:
          memory: 1g
          cpus: '1.0'
    networks:
      - ddf1-solr
  
  ddf2:
    image: codice/ddf:2.14.0-SNAPSHOT
    environment:
      SOLR_URL: "http://ddf2-solr:8983/solr"
      EXTERNAL_HTTPS_PORT: 443
      EXTERNAL_HTTP_PORT: 80
      JAVA_MAX_MEM: ${DIB_JAVA_MEM:-4}
      INSTALL_PROFILE: standard
      SSH_ENABLED: 'true'
    tty: true
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          memory: 3g
          cpus: '1.0'
      labels:
        - "traefik.enable=true"
        - "traefik.https.frontend.rule=Host: ddf2${DEPLOY_HOSTNAME_SUFFIX}.${DEPLOY_DOMAIN:-test}"
        - "traefik.https.protocol=https"
        - "traefik.https.port=8993"
        - "traefik.https.frontend.entryPoints=https"
        - "traefik.http.frontend.rule=Host: ddf2${DEPLOY_HOSTNAME_SUFFIX}.${DEPLOY_DOMAIN:-test}"
        - "traefik.http.protocol=http"
        - "traefik.http.port=8181"
        - "traefik.http.frontend.entryPoints=http"
    hostname: ddf2${DEPLOY_HOSTNAME_SUFFIX}.${DEPLOY_DOMAIN:-test}
    networks:
      - proxy
      - default
      - ddf2-solr

  ddf2-solr:
    image: codice/ddf-solr:2.14.0-SNAPSHOT
    environment:
      CORES: "catalog metacard_cache alerts preferences subscriptions notification activity workspace"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.5'
        reservations:
          memory: 1g
          cpus: '1.0'
    networks:
      - ddf2-solr

networks:
  proxy:
    external: true
  default:
  ddf1-solr:
  ddf2-solr:
